//
//  TestPresenter.swift
//  Dynamics Demo
//
//  Created DINH VAN TIEN on 6/2/19.
//  Copyright © 2019 Joyce Echessa. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class TestPresenter: TestPresenterProtocol {

    weak private var view: TestViewProtocol?
    var interactor: TestInteractorInputProtocol?
    private let router: TestWireframeProtocol

    init(interface: TestViewProtocol, interactor: TestInteractorInputProtocol?, router: TestWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

extension TestPresenter: TestInteractorOutputProtocol {

}
