//
//  TestViewController.swift
//  Dynamics Demo
//
//  Created DINH VAN TIEN on 6/2/19.
//  Copyright © 2019 Joyce Echessa. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class TestViewController: UIViewController {

	var presenter: TestPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}

extension TestViewController: TestViewProtocol {

}
