//
//  TestRouter.swift
//  Dynamics Demo
//
//  Created DINH VAN TIEN on 6/2/19.
//  Copyright © 2019 Joyce Echessa. All rights reserved.
//
//  Template generated by Tien Dinh
//

import UIKit

class TestRouter: TestWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = TestViewController(nibName: nil, bundle: nil)
        let interactor = TestInteractor()
        let router = TestRouter()
        let presenter = TestPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
