//
//  TestProtocols.swift
//  Dynamics Demo
//
//  Created DINH VAN TIEN on 6/2/19.
//  Copyright © 2019 Joyce Echessa. All rights reserved.
//
//  Template generated by Tien Dinh
//

import Foundation

//MARK: Wireframe -
protocol TestWireframeProtocol: class {

}
//MARK: Presenter -
protocol TestPresenterProtocol: class {

    var interactor: TestInteractorInputProtocol? { get set }
    
}

//MARK: Interactor -
protocol TestInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol TestInteractorInputProtocol: class {

    var presenter: TestInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol TestViewProtocol: class {

    var presenter: TestPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
