//
//  HomeInteractor.swift
//  LeftMenuDemo
//
//  Created DINH VAN TIEN on 4/24/19.
//  Copyright © 2019 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorInputProtocol {

    weak var presenter: HomeInteractorOutputProtocol?
}
