# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
#platform :ios, '9.0'
use_frameworks!
target 'EpubDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  inhibit_all_warnings!

  pod 'FolioReaderKit'
  pod 'EpubExtractor'

  # Pods for EpubDemo

end
