# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
 use_frameworks!
target 'TestExtractFile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

pod 'EpubExtractor'
pod 'RealmSwift'
pod 'MenuItemKit'
pod 'ZFDragableModalTransition'
pod 'FontBlaster'
#pod 'FolioReaderKit'

  # Pods for TestExtractFile

end
