//
//  MenuProtocols.swift
//  LeftMenuDemo
//
//  Created DINH VAN TIEN on 5/4/19.
//  Copyright © 2019 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol MenuWireframeProtocol: class {

}
//MARK: Presenter -
protocol MenuPresenterProtocol: class {

    var interactor: MenuInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol MenuInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol MenuInteractorInputProtocol: class {

    var presenter: MenuInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol MenuViewProtocol: class {

    var presenter: MenuPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
