//
//  MenuRouter.swift
//  LeftMenuDemo
//
//  Created DINH VAN TIEN on 5/4/19.
//  Copyright © 2019 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuRouter: MenuWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MenuViewController(nibName: nil, bundle: nil)
        let interactor = MenuInteractor()
        let router = MenuRouter()
        let presenter = MenuPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
