//
//  MenuInteractor.swift
//  LeftMenuDemo
//
//  Created DINH VAN TIEN on 5/4/19.
//  Copyright © 2019 DINH VAN TIEN. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuInteractor: MenuInteractorInputProtocol {

    weak var presenter: MenuInteractorOutputProtocol?
}
